@echo off
echo 启动AI漫剧工坊开发服务器...
echo.

echo 1. 启动前端开发服务器...
start "Frontend Server" cmd /k "cd frontend && npm start"

echo 2. 等待前端服务器启动...
timeout /t 5 /nobreak >nul

echo 3. 启动Electron主进程...
echo 正在启动Electron应用...
ts-node main.ts

pause